APP_TIMEZONE=Asia/Jakarta
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:xGOPLGKxuUhgAyUemtVOGjbi0jvff+wBKG9UIR10VMI=
APP_DEBUG=true
APP_URL=http://milink.id

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_DATABASE=u752471078_milink
DB_USERNAME=u752471078_milink
DB_PASSWORD=Milinkaja!1

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=milink.idn@gmail.com
MAIL_PASSWORD=xcljxnwuhsayblfz
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS='milink.idn@gmail.com'
MAIL_FROM_NAME='MiLink'

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=1689760
PUSHER_APP_KEY=9d7f8e80d07f08c3b69c
PUSHER_APP_SECRET=23bf39c46347f4264406
PUSHER_HOST=
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=ap1

VITE_APP_NAME="${APP_NAME}"
VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="${PUSHER_HOST}"
VITE_PUSHER_PORT="${PUSHER_PORT}"
VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

TRIPAY_API_KEY=mDzKZ7Io5FS9cZO94RJ3upsuNUF7otAAaMMSS91s
TRIPAY_PRIVATE_KEY=zweBk-5pVG0-EoG1p-Ujvxs-qBiVv
TRIPAY_MERCHANT_CODE=T27494
TRIPAY_MERCHANT_CODE=T27494

GOOGLE_CLIENT_ID=947706442816-3rvfo4n7gllqlqsg33tijmkc8cgsbeaq.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
GOOGLE_REDIRECT_URI=https://milink.id/id/google/redirect

FACEBOOK_CLIENT_ID=639564148314511
FACEBOOK_CLIENT_SECRET=6221fba41020881ee12661f4f5211b04
FACEBOOK_REDIRECT_URI=https://milink.id/id/facebook/redirect